### ISSUE TITLE
Prisma deploy

### ISSUE THREAD

**Issue by maarteNNNN** [akoenig/prisma-kubernetes-deployment#4]
First of all amazing tutorial!

Just a question. Let's say we make 10 replica's. And I run `prisma deploy` on one pod. Do all the other pods get the change?

**Comment by akoenig** [comment]
Thanks @maarteNNNN. Glad that your like it. 🙂

Yes, because the actual service configuration will be stored in the MySQL instance. You can find it in the “graphcool” database. Please note that when replicating the Prisma server, you also have to make sure to scale MySQL as well. Otherwise this part will be your bottleneck.
